[package]
name = "engine"
version = "0.1.0"
authors = ["tonis2 <tonis.anton18@gmail.com>"]
edition = "2018"

[dependencies]
arrayvec = "0.4"
cgmath = "0.17"
env_logger = "0.6"
glsl-to-spirv = "0.1"
log = "0.4"
uuid = { version = "0.7", features = ["serde", "v4"] }


[dependencies.wgpu]
git = "https://github.com/gfx-rs/wgpu-rs.git"
rev = "a05eab15a1efeb9c5ac49c0b4bd2620bcf850a3a"
version = "*"
features = ["vulkan"]
